// <auto-generated />
namespace WWUD2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class question_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(question_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201512271845011_question_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
